# Copyright Contributors to the Open Cluster Management project

kind: Deployment
apiVersion: apps/v1
metadata:
  name: clusterlifecycle-state-metrics
  namespace: open-cluster-management
spec:
  template:
    spec:
      containers:
      - name: clusterlifecycle-state-metrics
        image: quay.io/stolostron/clusterlifecycle-state-metrics:REPLACE_IMAGE
